name: myenvr
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - scanpy~=1.9.1
  - numpy~=1.21.6
  - gdown~=4.4.0
  - leidenalg==0.8.9
  - scikit-misc==0.1.4
  - protobuf==3.19.4
  - pymde==0.1.15
  - flask==2.1.1
  - uwsgi==2.0.20
  - gunicorn==20.1.0
  - boto3==1.22.1
  - r-sceasy
  - pip
  - rpy2
  - pip:
      - scarches~=0.5.2
      - scvi-tools==0.16.1
      - torch~=1.11.0
