FROM python:3.9 as cellxgene-build

RUN pip install cellxgene gcsfs

COPY . .
    
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:slim
# TODO: Maybe you don't need to install anything and auth is already installed 
# RUN gcloud components install auth

# Copy everything from the first layer
COPY --from=cellxgene-build . .
EXPOSE ${PORT}
# Container timeout in seconds 
ENV TIMEOUT=60

#GCloud-specific environmental variables
ENV SERVICE_ACCOUNT_EMAIL="google-cloud-run-service-local@custom-helix-329116.iam.gserviceaccount.com"
ENV GOOGLE_APPLICATION_CREDENTIALS="/service_account_key/custom-helix-329116-fb3fb8908455.json"
ENV PROJECT_ID="custom-helix-329116"

# gcloud-specific configuration
RUN gcloud auth activate-service-account ${SERVICE_ACCOUNT_EMAIL} --project=${PROJECT_ID} --key-file=${GOOGLE_APPLICATION_CREDENTIALS}

CMD cellxgene launch --host 0.0.0.0 ${GCS_FILE_LOCATION}

#TODO: use gsutil rsync to sync the annotated data with the google cloud storage. 